### PR TITLE
Create algorithmSimplified.py

### PR DESCRIPTION
**Pull request by infizer91**
Python 3

### CODE REVIEW

**Comment by ludwig-v** [comment]
Please respect the license, removing copyright disclaimer is not allowed

**Comment by prototux** [comment]
@infizer91 thanks for your python port! can i add it to my psa-re repository? (with credit of course!), the repository is under the apache2 licence, so your code would probably end under that licence as well, if you're ok with that :)

**Comment by infizer91** [comment]
> @prototux, ok, i agree :)

**Comment by prototux** [comment]
@infizer91 i'll do it later this evening then, thanks! :grinning: 

I'll put it there: https://github.com/prototux/PSA-RE/tree/master/sandbox (the whole repo is not only for the UDS, but a general repository for reverse engineering PSA's CAN and VAN buses (including the diagnostic data), to help people create cool project on PSA's car :grin: )

If you're interested in a welcoming (and currently quite active) community around these kind of projects, there's a link to the discord on PSA-RE's README :wink:  and of course, contributions are welcome!

**Pull request closed without merging**
